// <auto-generated/>
// Generated from native DAT interchange definitions. DAT packing stays native.
#nullable enable
using System.Numerics;
using MessagePack;

namespace Acme.Dat;

/// <summary>Ordered HashMap entry matching native DAT interchange.</summary>
[MessagePackObject]
public sealed class MapEntry<TKey, TValue> {
    [Key("key")] public TKey Key { get; set; } = default!;
    [Key("value")] public TValue Value { get; set; } = default!;
}

public interface IDatRecord {
    void AfterDeserialize();
    void BeforeSerialize();
}

[MessagePackObject]
public sealed partial class LandBlock : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("has_objects")] public bool HasObjects { get; set; }
    [Key("terrain")] public ushort[] Terrain { get; set; } = [];
    [Key("height")] public byte[] Height { get; set; } = [];
    [Key("padding")] public byte Padding { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Stab : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("origin")] public float[] OriginArray { get; set; } = [0, 0, 0];
    [Key("angles")] public float[] AnglesArray { get; set; } = [0, 0, 0, 1];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class BuildingPortal : IDatRecord {
    [Key("flags")] public ushort Flags { get; set; }
    [Key("other_cell_id")] public ushort OtherCellId { get; set; }
    [Key("other_portal_id")] public ushort OtherPortalId { get; set; }
    [Key("stab_cells")] public List<ushort> StabCells { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class BuildingInfo : IDatRecord {
    [Key("model_id")] public uint ModelId { get; set; }
    [Key("origin")] public float[] OriginArray { get; set; } = [0, 0, 0];
    [Key("angles")] public float[] AnglesArray { get; set; } = [0, 0, 0, 1];
    [Key("num_leaves")] public uint NumLeaves { get; set; }
    [Key("portals")] public List<BuildingPortal> Portals { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class LandBlockInfo : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("num_cells")] public uint NumCells { get; set; }
    [Key("objects")] public List<Stab> Objects { get; set; } = [];
    [Key("buildings")] public List<BuildingInfo> Buildings { get; set; } = [];
    [Key("pack_mask")] public ushort PackMask { get; set; }
    [Key("restrictions")] public List<(uint, uint)> Restrictions { get; set; } = [];
    [Key("restriction_buckets")] public ushort RestrictionBuckets { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CellPortal : IDatRecord {
    [Key("flags")] public ushort Flags { get; set; }
    [Key("polygon_id")] public ushort PolygonId { get; set; }
    [Key("other_cell_id")] public ushort OtherCellId { get; set; }
    [Key("other_portal_id")] public ushort OtherPortalId { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class EnvCell : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("flags")] public uint Flags { get; set; }
    [Key("surfaces")] public List<uint> Surfaces { get; set; } = [];
    [Key("environment_id")] public uint EnvironmentId { get; set; }
    [Key("cell_structure")] public ushort CellStructure { get; set; }
    [Key("position_origin")] public float[] PositionOriginArray { get; set; } = [0, 0, 0];
    [Key("position_quat")] public float[] PositionQuatArray { get; set; } = [0, 0, 0, 1];
    [Key("cell_portals")] public List<CellPortal> CellPortals { get; set; } = [];
    [Key("visible_cells")] public List<ushort> VisibleCells { get; set; } = [];
    [Key("static_objects")] public List<Stab> StaticObjects { get; set; } = [];
    [Key("restriction_obj")] public uint? RestrictionObjNullable { get; set; }
    [Key("id_echo")] public uint IdEcho { get; set; }
    [Key("trailing_data")] public byte[] TrailingData { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Frame : IDatRecord {
    [Key("origin")] public float[] OriginArray { get; set; } = [0, 0, 0];
    [Key("orientation")] public float[] OrientationArray { get; set; } = [0, 0, 0, 1];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SetupLocation : IDatRecord {
    [Key("part_id")] public uint PartId { get; set; }
    [Key("frame")] public Frame Frame { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SetupPlacement : IDatRecord {
    [Key("key")] public uint Key { get; set; }
    [Key("part_frames")] public List<Frame> PartFrames { get; set; } = [];
    [Key("hook_data")] public byte[] HookData { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CylSphere : IDatRecord {
    [Key("x")] public float X { get; set; }
    [Key("y")] public float Y { get; set; }
    [Key("z")] public float Z { get; set; }
    [Key("radius")] public float Radius { get; set; }
    [Key("height")] public float Height { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Sphere : IDatRecord {
    [Key("x")] public float X { get; set; }
    [Key("y")] public float Y { get; set; }
    [Key("z")] public float Z { get; set; }
    [Key("radius")] public float Radius { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SetupLightColor : IDatRecord {
    [Key("blue")] public byte Blue { get; set; }
    [Key("green")] public byte Green { get; set; }
    [Key("red")] public byte Red { get; set; }
    [Key("alpha")] public byte Alpha { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class LightInfo : IDatRecord {
    [Key("view_space_location")] public Frame ViewSpaceLocation { get; set; } = new();
    [Key("color")] public SetupLightColor Color { get; set; } = new();
    [Key("retail_color_bits")] public uint[]? RetailColorBits { get; set; }
    [Key("intensity")] public float Intensity { get; set; }
    [Key("falloff")] public float Falloff { get; set; }
    [Key("cone_angle")] public float ConeAngle { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Setup : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("packed_light_colors")] public bool PackedLightColors { get; set; }
    [Key("flags")] public uint Flags { get; set; }
    [Key("num_parts")] public uint NumParts { get; set; }
    [Key("parts")] public List<uint> Parts { get; set; } = [];
    [Key("parent_index")] public List<uint> ParentIndex { get; set; } = [];
    [Key("default_scale")] public List<float[]> DefaultScale { get; set; } = [];
    [Key("holding_locations")] public List<MapEntry<uint, SetupLocation>> HoldingLocationsEntries { get; set; } = [];
    [Key("holding_location_entry_order")] public List<uint> HoldingLocationEntryOrder { get; set; } = [];
    [Key("connection_points")] public List<MapEntry<uint, SetupLocation>> ConnectionPointsEntries { get; set; } = [];
    [Key("connection_point_entry_order")] public List<uint> ConnectionPointEntryOrder { get; set; } = [];
    [Key("placement_frames")] public List<SetupPlacement> PlacementFrameList { get; set; } = [];
    [Key("cyl_spheres")] public List<CylSphere> CylSpheres { get; set; } = [];
    [Key("spheres")] public List<Sphere> Spheres { get; set; } = [];
    [Key("has_physics_bsp")] public bool HasPhysicsBsp { get; set; }
    [Key("allow_free_heading")] public bool AllowFreeHeading { get; set; }
    [Key("height")] public float Height { get; set; }
    [Key("radius")] public float Radius { get; set; }
    [Key("step_up_height")] public float StepUpHeight { get; set; }
    [Key("step_down_height")] public float StepDownHeight { get; set; }
    [Key("sorting_sphere")] public Sphere SortingSphere { get; set; } = new();
    [Key("selection_sphere")] public Sphere SelectionSphere { get; set; } = new();
    [Key("lights")] public List<MapEntry<uint, LightInfo>> LightsEntries { get; set; } = [];
    [Key("light_entry_order")] public List<uint> LightEntryOrder { get; set; } = [];
    [Key("default_anim_id")] public uint DefaultAnimId { get; set; }
    [Key("default_script_id")] public uint DefaultScriptId { get; set; }
    [Key("default_mtable_id")] public uint DefaultMtableId { get; set; }
    [Key("default_stable_id")] public uint DefaultStableId { get; set; }
    [Key("default_phstable_id")] public uint DefaultPhstableId { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class ObjectDesc : IDatRecord {
    [Key("object_id")] public uint ObjectId { get; set; }
    [Key("origin")] public float[] OriginArray { get; set; } = [0, 0, 0];
    [Key("orientation")] public float[] OrientationArray { get; set; } = [0, 0, 0, 1];
    [Key("frequency")] public float Frequency { get; set; }
    [Key("displace_x")] public float DisplaceX { get; set; }
    [Key("displace_y")] public float DisplaceY { get; set; }
    [Key("min_scale")] public float MinScale { get; set; }
    [Key("max_scale")] public float MaxScale { get; set; }
    [Key("max_rotation")] public float MaxRotation { get; set; }
    [Key("min_slope")] public float MinSlope { get; set; }
    [Key("max_slope")] public float MaxSlope { get; set; }
    [Key("align")] public uint Align { get; set; }
    [Key("orient")] public uint Orient { get; set; }
    [Key("weenie_obj")] public uint WeenieObj { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Scene : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("objects")] public List<ObjectDesc> Objects { get; set; } = [];
    [Key("trailing_bytes")] public int TrailingBytes { get; set; }
    [Key("trailing_data")] public byte[] TrailingData { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Palette : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("colors")] public List<uint> Colors { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Surface : IDatRecord {
    [Key("stype")] public uint Stype { get; set; }
    [Key("orig_texture_id")] public uint OrigTextureId { get; set; }
    [Key("orig_palette_id")] public uint OrigPaletteId { get; set; }
    [Key("color_value")] public uint ColorValue { get; set; }
    [Key("translucency")] public float Translucency { get; set; }
    [Key("luminosity")] public float Luminosity { get; set; }
    [Key("diffuse")] public float Diffuse { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SurfaceTexture : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("data_category")] public uint DataCategory { get; set; }
    [Key("texture_type")] public byte TextureType { get; set; }
    [Key("textures")] public List<uint> Textures { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class RenderTexture : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("data_category")] public uint DataCategory { get; set; }
    [Key("texture_type")] public byte TextureType { get; set; }
    [Key("source_levels")] public List<uint> SourceLevels { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class RenderSurface : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("data_category")] public uint DataCategory { get; set; }
    [Key("width")] public int Width { get; set; }
    [Key("height")] public int Height { get; set; }
    [Key("format")] public uint Format { get; set; }
    [Key("source_data")] public byte[] SourceData { get; set; } = [];
    [Key("default_palette_id")] public uint DefaultPaletteId { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class ParticleEmitter : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("unknown")] public uint Unknown { get; set; }
    [Key("emitter_type")] public int EmitterType { get; set; }
    [Key("particle_type")] public int ParticleType { get; set; }
    [Key("gfx_obj_id")] public uint GfxObjId { get; set; }
    [Key("hw_gfx_obj_id")] public uint HwGfxObjId { get; set; }
    [Key("birthrate")] public double Birthrate { get; set; }
    [Key("max_particles")] public int MaxParticles { get; set; }
    [Key("initial_particles")] public int InitialParticles { get; set; }
    [Key("total_particles")] public int TotalParticles { get; set; }
    [Key("total_seconds")] public double TotalSeconds { get; set; }
    [Key("lifespan")] public double Lifespan { get; set; }
    [Key("lifespan_rand")] public double LifespanRand { get; set; }
    [Key("offset_dir")] public float[] OffsetDirArray { get; set; } = [0, 0, 0];
    [Key("min_offset")] public float MinOffset { get; set; }
    [Key("max_offset")] public float MaxOffset { get; set; }
    [Key("a")] public float[] AArray { get; set; } = [0, 0, 0];
    [Key("min_a")] public float MinA { get; set; }
    [Key("max_a")] public float MaxA { get; set; }
    [Key("b")] public float[] BArray { get; set; } = [0, 0, 0];
    [Key("min_b")] public float MinB { get; set; }
    [Key("max_b")] public float MaxB { get; set; }
    [Key("c")] public float[] CArray { get; set; } = [0, 0, 0];
    [Key("min_c")] public float MinC { get; set; }
    [Key("max_c")] public float MaxC { get; set; }
    [Key("start_scale")] public float StartScale { get; set; }
    [Key("final_scale")] public float FinalScale { get; set; }
    [Key("scale_rand")] public float ScaleRand { get; set; }
    [Key("start_trans")] public float StartTrans { get; set; }
    [Key("final_trans")] public float FinalTrans { get; set; }
    [Key("trans_rand")] public float TransRand { get; set; }
    [Key("is_parent_local")] public bool IsParentLocal { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class LayoutDesc : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("width")] public uint Width { get; set; }
    [Key("height")] public uint Height { get; set; }
    [Key("elements_blob")] public byte[] ElementsBlob { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class StringTableString : IDatRecord {
    [Key("data_id")] public uint DataId { get; set; }
    [Key("strings")] public List<string> Strings { get; set; } = [];
    [Key("variables")] public List<uint> Variables { get; set; } = [];
    [Key("is_var_name_table_worth_packing")] public bool IsVarNameTableWorthPacking { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class StringTable : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("language")] public uint Language { get; set; }
    [Key("buckets")] public uint Buckets { get; set; }
    [Key("entries")] public List<MapEntry<uint, StringTableString>> EntriesEntries { get; set; } = [];
    [Key("entry_order")] public List<uint> EntryOrder { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CloTextureEffect : IDatRecord {
    [Key("old_texture")] public uint OldTexture { get; set; }
    [Key("new_texture")] public uint NewTexture { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CloObjectEffect : IDatRecord {
    [Key("part_index")] public uint PartIndex { get; set; }
    [Key("model_id")] public uint ModelId { get; set; }
    [Key("texture_effects")] public List<CloTextureEffect> TextureEffects { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class ClothingBaseEffect : IDatRecord {
    [Key("object_effects")] public List<CloObjectEffect> ObjectEffects { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CloSubPaletteRange : IDatRecord {
    [Key("offset")] public uint Offset { get; set; }
    [Key("num_colors")] public uint NumColors { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CloSubPalette : IDatRecord {
    [Key("ranges")] public List<CloSubPaletteRange> Ranges { get; set; } = [];
    [Key("palette_set")] public uint PaletteSet { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CloSubPalEffect : IDatRecord {
    [Key("icon")] public uint Icon { get; set; }
    [Key("sub_palettes")] public List<CloSubPalette> SubPalettes { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class ClothingTable : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("base_effect_bucket_count")] public ushort BaseEffectBucketCount { get; set; }
    [Key("base_effect_entry_order")] public List<uint> BaseEffectEntryOrder { get; set; } = [];
    [Key("base_effects")] public List<MapEntry<uint, ClothingBaseEffect>> BaseEffectsEntries { get; set; } = [];
    [Key("sub_pal_effect_bucket_count")] public ushort SubPalEffectBucketCount { get; set; }
    [Key("sub_pal_effect_entry_order")] public List<uint> SubPalEffectEntryOrder { get; set; } = [];
    [Key("sub_pal_effects")] public List<MapEntry<uint, CloSubPalEffect>> SubPalEffectsEntries { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class PalSet : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("palette_ids")] public List<uint> PaletteIds { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class ExperienceTable : IDatRecord {
    [Key("attribute_xp")] public List<uint> AttributeXp { get; set; } = [];
    [Key("vital_xp")] public List<uint> VitalXp { get; set; } = [];
    [Key("trained_skill_xp")] public List<uint> TrainedSkillXp { get; set; } = [];
    [Key("specialized_skill_xp")] public List<uint> SpecializedSkillXp { get; set; } = [];
    [Key("level_xp")] public List<ulong> LevelXp { get; set; } = [];
    [Key("skill_credits")] public List<uint> SkillCredits { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SkillFormula : IDatRecord {
    [Key("additive_bonus")] public int AdditiveBonus { get; set; }
    [Key("attr1_multiplier")] public int Attr1Multiplier { get; set; }
    [Key("attr2_multiplier")] public int Attr2Multiplier { get; set; }
    [Key("divisor")] public int Divisor { get; set; }
    [Key("attr1")] public uint Attr1 { get; set; }
    [Key("attr2")] public uint Attr2 { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SkillBase : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("description")] public string Description { get; set; } = "";
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("trained_cost")] public int TrainedCost { get; set; }
    [Key("specialized_cost")] public int SpecializedCost { get; set; }
    [Key("category")] public SkillCategory Category { get; set; }
    [Key("chargen_use")] public bool ChargenUse { get; set; }
    [Key("min_level")] public uint MinLevel { get; set; }
    [Key("formula")] public SkillFormula Formula { get; set; } = new();
    [Key("upper_bound")] public double UpperBound { get; set; }
    [Key("lower_bound")] public double LowerBound { get; set; }
    [Key("learn_mod")] public double LearnMod { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SkillTable : IDatRecord {
    [Key("bucket_count")] public ushort BucketCount { get; set; }
    [Key("entry_order")] public List<uint> EntryOrder { get; set; } = [];
    [Key("skills")] public List<MapEntry<uint, SkillBase>> SkillsEntries { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class VitalFormula : IDatRecord {
    [Key("additive_bonus")] public uint AdditiveBonus { get; set; }
    [Key("attr1_multiplier")] public uint Attr1Multiplier { get; set; }
    [Key("attr2_multiplier")] public uint Attr2Multiplier { get; set; }
    [Key("divisor")] public uint Divisor { get; set; }
    [Key("attr1")] public uint Attr1 { get; set; }
    [Key("attr2")] public uint Attr2 { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class VitalTable : IDatRecord {
    [Key("health")] public VitalFormula Health { get; set; } = new();
    [Key("stamina")] public VitalFormula Stamina { get; set; } = new();
    [Key("mana")] public VitalFormula Mana { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SpellBase : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("description")] public string Description { get; set; } = "";
    [Key("school")] public MagicSchool School { get; set; }
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("category")] public SpellCategory Category { get; set; }
    [Key("bitfield")] public uint Bitfield { get; set; }
    [Key("base_mana")] public uint BaseMana { get; set; }
    [Key("base_range_constant")] public float BaseRangeConstant { get; set; }
    [Key("base_range_mod")] public float BaseRangeMod { get; set; }
    [Key("power")] public uint Power { get; set; }
    [Key("spell_economy_mod")] public float SpellEconomyMod { get; set; }
    [Key("formula_version")] public uint FormulaVersion { get; set; }
    [Key("component_loss")] public float ComponentLoss { get; set; }
    [Key("meta_spell_type")] public SpellType MetaSpellType { get; set; }
    [Key("meta_spell_id")] public uint MetaSpellId { get; set; }
    [Key("duration")] public double Duration { get; set; }
    [Key("degrade_modifier")] public float DegradeModifier { get; set; }
    [Key("degrade_limit")] public float DegradeLimit { get; set; }
    [Key("portal_lifetime")] public double PortalLifetime { get; set; }
    [Key("component_ids")] public List<uint> ComponentIds { get; set; } = [];
    [Key("caster_effect")] public PlayScript CasterEffect { get; set; }
    [Key("target_effect")] public PlayScript TargetEffect { get; set; }
    [Key("fizzle_effect")] public PlayScript FizzleEffect { get; set; }
    [Key("recovery_interval")] public double RecoveryInterval { get; set; }
    [Key("recovery_amount")] public float RecoveryAmount { get; set; }
    [Key("display_order")] public uint DisplayOrder { get; set; }
    [Key("non_component_target_type")] public uint NonComponentTargetType { get; set; }
    [Key("mana_mod")] public uint ManaMod { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SpellTable : IDatRecord {
    [Key("buckets")] public ushort Buckets { get; set; }
    [Key("spell_ids")] public List<uint> SpellIds { get; set; } = [];
    [Key("spells")] public List<MapEntry<uint, SpellBase>> SpellsEntries { get; set; } = [];
    [Key("spell_set_buckets")] public ushort SpellSetBuckets { get; set; }
    [Key("spell_set_ids")] public List<uint> SpellSetIds { get; set; } = [];
    [Key("spell_sets")] public List<MapEntry<uint, SpellSet>> SpellSetsEntries { get; set; } = [];
    [Key("spell_sets_raw")] public byte[] SpellSetsRaw { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SpellComponentBase : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("category")] public uint Category { get; set; }
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("component_type")] public uint ComponentType { get; set; }
    [Key("gesture")] public uint Gesture { get; set; }
    [Key("time")] public float Time { get; set; }
    [Key("text")] public string Text { get; set; } = "";
    [Key("cdm")] public float Cdm { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SpellComponentTable : IDatRecord {
    [Key("buckets")] public ushort Buckets { get; set; }
    [Key("component_ids")] public List<uint> ComponentIds { get; set; } = [];
    [Key("components")] public List<MapEntry<uint, SpellComponentBase>> ComponentsEntries { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Polygon : IDatRecord {
    [Key("stippling")] public StipplingType Stippling { get; set; }
    [Key("sides_type")] public int SidesType { get; set; }
    [Key("pos_surface")] public short PosSurface { get; set; }
    [Key("neg_surface")] public short NegSurface { get; set; }
    [Key("vertex_ids")] public List<ushort> VertexIds { get; set; } = [];
    [Key("pos_uv_indices")] public List<byte> PosUvIndices { get; set; } = [];
    [Key("neg_uv_indices")] public List<byte> NegUvIndices { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class GfxVertex : IDatRecord {
    [Key("origin")] public float[] OriginArray { get; set; } = [0, 0, 0];
    [Key("normal")] public float[] NormalArray { get; set; } = [0, 0, 0];
    [Key("uvs")] public List<float[]> Uvs { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class GfxObjPhysics : IDatRecord {
    [Key("raw_polygons")] public List<MapEntry<uint, Polygon>> RawPolygonsEntries { get; set; } = [];
    [Key("raw_polygon_entry_order")] public List<uint> RawPolygonEntryOrder { get; set; } = [];
    [Key("physics_bsp_bytes")] public byte[] PhysicsBspBytes { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class GfxObj : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("flags")] public uint Flags { get; set; }
    [Key("surfaces")] public List<uint> Surfaces { get; set; } = [];
    [Key("vertex_type")] public int VertexType { get; set; }
    [Key("vertices")] public List<MapEntry<ushort, float[]>> VerticesEntries { get; set; } = [];
    [Key("vertex_entry_order")] public List<ushort> VertexEntryOrder { get; set; } = [];
    [Key("render_vertices")] public List<MapEntry<ushort, GfxVertex>> RenderVerticesEntries { get; set; } = [];
    [Key("drawing_polygons")] public List<MapEntry<uint, Polygon>> DrawingPolygonsEntries { get; set; } = [];
    [Key("drawing_polygon_entry_order")] public List<uint> DrawingPolygonEntryOrder { get; set; } = [];
    [Key("drawing_bsp_bytes")] public byte[] DrawingBspBytes { get; set; } = [];
    [Key("sort_center")] public float[] SortCenterArray { get; set; } = [0, 0, 0];
    [Key("physics")] public GfxObjPhysics? Physics { get; set; }
    [Key("degrade_did")] public uint? DegradeDid { get; set; }
    [Key("trailing_data")] public byte[] TrailingData { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CellStruct : IDatRecord {
    [Key("vertex_type")] public int VertexType { get; set; }
    [Key("vertices")] public List<MapEntry<ushort, float[]>> VerticesEntries { get; set; } = [];
    [Key("vertex_entry_order")] public List<ushort> VertexEntryOrder { get; set; } = [];
    [Key("render_vertices")] public List<MapEntry<ushort, GfxVertex>> RenderVerticesEntries { get; set; } = [];
    [Key("polygons")] public List<MapEntry<uint, Polygon>> PolygonsEntries { get; set; } = [];
    [Key("polygon_entry_order")] public List<uint> PolygonEntryOrder { get; set; } = [];
    [Key("portals")] public List<ushort> Portals { get; set; } = [];
    [Key("cell_bsp_bytes")] public byte[] CellBspBytes { get; set; } = [];
    [Key("raw_physics_polygons")] public List<MapEntry<uint, Polygon>> RawPhysicsPolygonsEntries { get; set; } = [];
    [Key("raw_physics_polygon_entry_order")] public List<uint> RawPhysicsPolygonEntryOrder { get; set; } = [];
    [Key("physics_bsp_bytes")] public byte[] PhysicsBspBytes { get; set; } = [];
    [Key("drawing_tail_bytes")] public byte[] DrawingTailBytes { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Environment : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("cells")] public List<MapEntry<uint, CellStruct>> CellsEntries { get; set; } = [];
    [Key("cell_entry_order")] public List<uint> CellEntryOrder { get; set; } = [];
    [Key("cell_count")] public uint CellCount { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class LandDefs : IDatRecord {
    [Key("num_block_length")] public uint NumBlockLength { get; set; }
    [Key("num_block_width")] public uint NumBlockWidth { get; set; }
    [Key("square_length")] public float SquareLength { get; set; }
    [Key("lblock_length")] public uint LblockLength { get; set; }
    [Key("vertex_per_cell")] public uint VertexPerCell { get; set; }
    [Key("max_obj_height")] public float MaxObjHeight { get; set; }
    [Key("sky_height")] public float SkyHeight { get; set; }
    [Key("road_width")] public float RoadWidth { get; set; }
    [Key("land_height_table")] public float[] LandHeightTable { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TimeOfDay : IDatRecord {
    [Key("start")] public float Start { get; set; }
    [Key("is_night")] public bool IsNight { get; set; }
    [Key("name")] public string Name { get; set; } = "";
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Season : IDatRecord {
    [Key("start_day")] public uint StartDay { get; set; }
    [Key("name")] public string Name { get; set; } = "";
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class GameTime : IDatRecord {
    [Key("zero_time_of_year")] public double ZeroTimeOfYear { get; set; }
    [Key("zero_year")] public uint ZeroYear { get; set; }
    [Key("day_length")] public float DayLength { get; set; }
    [Key("days_per_year")] public uint DaysPerYear { get; set; }
    [Key("year_spec")] public string YearSpec { get; set; } = "";
    [Key("times_of_day")] public List<TimeOfDay> TimesOfDay { get; set; } = [];
    [Key("days_of_week")] public List<string> DaysOfWeek { get; set; } = [];
    [Key("seasons")] public List<Season> Seasons { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SceneType : IDatRecord {
    [Key("ambient_sound_table")] public uint AmbientSoundTable { get; set; }
    [Key("dids")] public List<uint> Dids { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TerrainType : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("colour")] public uint Colour { get; set; }
    [Key("scene_type_indices")] public List<uint> SceneTypeIndices { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TerrainAlphaMap : IDatRecord {
    [Key("tcode")] public uint Tcode { get; set; }
    [Key("texture_id")] public uint TextureId { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class RoadAlphaMap : IDatRecord {
    [Key("rcode")] public uint Rcode { get; set; }
    [Key("texture_id")] public uint TextureId { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TerrainTex : IDatRecord {
    [Key("texture_id")] public uint TextureId { get; set; }
    [Key("tex_tiling")] public uint TexTiling { get; set; }
    [Key("max_vert_bright")] public uint MaxVertBright { get; set; }
    [Key("min_vert_bright")] public uint MinVertBright { get; set; }
    [Key("max_vert_saturate")] public uint MaxVertSaturate { get; set; }
    [Key("min_vert_saturate")] public uint MinVertSaturate { get; set; }
    [Key("max_vert_hue")] public uint MaxVertHue { get; set; }
    [Key("min_vert_hue")] public uint MinVertHue { get; set; }
    [Key("detail_tex_tiling")] public uint DetailTexTiling { get; set; }
    [Key("detail_texture_id")] public uint DetailTextureId { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TMTerrainDesc : IDatRecord {
    [Key("terrain_type")] public TerrainTextureType TerrainType { get; set; }
    [Key("terrain_tex")] public TerrainTex TerrainTex { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TexMerge : IDatRecord {
    [Key("base_tex_size")] public uint BaseTexSize { get; set; }
    [Key("corner_terrain_maps")] public List<TerrainAlphaMap> CornerTerrainMaps { get; set; } = [];
    [Key("side_terrain_maps")] public List<TerrainAlphaMap> SideTerrainMaps { get; set; } = [];
    [Key("road_maps")] public List<RoadAlphaMap> RoadMaps { get; set; } = [];
    [Key("terrain_desc")] public List<TMTerrainDesc> TerrainDesc { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class LandSurf : IDatRecord {
    [Key("type")] public uint Type { get; set; }
    [Key("tex_merge")] public TexMerge TexMerge { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Region : IDatRecord {
    [Key("id")] public uint Id { get; set; }
    [Key("region_number")] public uint RegionNumber { get; set; }
    [Key("version")] public uint Version { get; set; }
    [Key("name")] public string Name { get; set; } = "";
    [Key("land_defs")] public LandDefs LandDefs { get; set; } = new();
    [Key("game_time")] public GameTime GameTime { get; set; } = new();
    [Key("parts_mask")] public uint PartsMask { get; set; }
    [Key("sky_desc_bytes")] public byte[] SkyDescBytes { get; set; } = [];
    [Key("sound_desc_bytes")] public byte[] SoundDescBytes { get; set; } = [];
    [Key("scene_types")] public List<SceneType> SceneTypes { get; set; } = [];
    [Key("terrain_types")] public List<TerrainType> TerrainTypes { get; set; } = [];
    [Key("land_surf")] public LandSurf? LandSurf { get; set; }
    [Key("land_surf_suffix")] public byte[] LandSurfSuffix { get; set; } = [];
    [Key("land_surf_bytes")] public byte[] LandSurfBytes { get; set; } = [];
    [Key("raw_after_parts_mask")] public bool RawAfterPartsMask { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SubPalette : IDatRecord {
    [Key("palette_did")] public uint PaletteDid { get; set; }
    [Key("offset")] public byte Offset { get; set; }
    [Key("length")] public byte Length { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TextureMapChange : IDatRecord {
    [Key("part_index")] public byte PartIndex { get; set; }
    [Key("old_texture_did")] public uint OldTextureDid { get; set; }
    [Key("new_texture_did")] public uint NewTextureDid { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class AnimPartChange : IDatRecord {
    [Key("part_index")] public byte PartIndex { get; set; }
    [Key("new_model_did")] public uint NewModelDid { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class ObjDesc : IDatRecord {
    [Key("flags")] public byte Flags { get; set; }
    [Key("base_palette")] public uint? BasePalette { get; set; }
    [Key("sub_palettes")] public List<SubPalette> SubPalettes { get; set; } = [];
    [Key("texture_changes")] public List<TextureMapChange> TextureChanges { get; set; } = [];
    [Key("model_changes")] public List<AnimPartChange> ModelChanges { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class Position : IDatRecord {
    [Key("cell_id")] public uint CellId { get; set; }
    [Key("origin")] public float[] OriginArray { get; set; } = [0, 0, 0];
    [Key("orientation")] public float[] OrientationArray { get; set; } = [0, 0, 0, 1];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class StartArea : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("locations")] public List<Position> Locations { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SkillCG : IDatRecord {
    [Key("skill_id")] public int SkillId { get; set; }
    [Key("normal_cost")] public int NormalCost { get; set; }
    [Key("primary_cost")] public int PrimaryCost { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class TemplateCG : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("title")] public uint Title { get; set; }
    [Key("strength")] public int Strength { get; set; }
    [Key("endurance")] public int Endurance { get; set; }
    [Key("coordination")] public int Coordination { get; set; }
    [Key("quickness")] public int Quickness { get; set; }
    [Key("focus")] public int Focus { get; set; }
    [Key("self_stat")] public int SelfStat { get; set; }
    [Key("trained_skills")] public List<int> TrainedSkills { get; set; } = [];
    [Key("specialized_skills")] public List<int> SpecializedSkills { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class GearCG : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("clothing_table")] public uint ClothingTable { get; set; }
    [Key("weenie_default")] public uint WeenieDefault { get; set; }
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class HairStyleCG : IDatRecord {
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("bald")] public bool Bald { get; set; }
    [Key("alternate_setup")] public uint AlternateSetup { get; set; }
    [Key("obj_desc")] public ObjDesc ObjDesc { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class EyeStripCG : IDatRecord {
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("bald_icon_id")] public uint BaldIconId { get; set; }
    [Key("obj_desc")] public ObjDesc ObjDesc { get; set; } = new();
    [Key("bald_obj_desc")] public ObjDesc BaldObjDesc { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class FaceStripCG : IDatRecord {
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("obj_desc")] public ObjDesc ObjDesc { get; set; } = new();
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class SexCG : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("scale")] public uint Scale { get; set; }
    [Key("setup_did")] public uint SetupDid { get; set; }
    [Key("sound_table_did")] public uint SoundTableDid { get; set; }
    [Key("icon_did")] public uint IconDid { get; set; }
    [Key("base_palette_did")] public uint BasePaletteDid { get; set; }
    [Key("skin_palette_did")] public uint SkinPaletteDid { get; set; }
    [Key("physics_table_did")] public uint PhysicsTableDid { get; set; }
    [Key("combat_table_did")] public uint CombatTableDid { get; set; }
    [Key("motion_table_did")] public uint MotionTableDid { get; set; }
    [Key("base_obj_desc")] public ObjDesc BaseObjDesc { get; set; } = new();
    [Key("hair_colors")] public List<uint> HairColors { get; set; } = [];
    [Key("hair_styles")] public List<HairStyleCG> HairStyles { get; set; } = [];
    [Key("eye_colors")] public List<uint> EyeColors { get; set; } = [];
    [Key("eye_strips")] public List<EyeStripCG> EyeStrips { get; set; } = [];
    [Key("nose_strips")] public List<FaceStripCG> NoseStrips { get; set; } = [];
    [Key("mouth_strips")] public List<FaceStripCG> MouthStrips { get; set; } = [];
    [Key("clothing_colors")] public List<uint> ClothingColors { get; set; } = [];
    [Key("headgear_list")] public List<GearCG> HeadgearList { get; set; } = [];
    [Key("shirt_list")] public List<GearCG> ShirtList { get; set; } = [];
    [Key("pants_list")] public List<GearCG> PantsList { get; set; } = [];
    [Key("footwear_list")] public List<GearCG> FootwearList { get; set; } = [];
    [Key("skin_palettes")] public List<uint> SkinPalettes { get; set; } = [];
    [Key("hair_color_palettes")] public List<List<uint>> HairColorPalettes { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class HeritageGroupCG : IDatRecord {
    [Key("name")] public string Name { get; set; } = "";
    [Key("icon_id")] public uint IconId { get; set; }
    [Key("setup_id")] public uint SetupId { get; set; }
    [Key("environment_setup_id")] public uint EnvironmentSetupId { get; set; }
    [Key("attribute_credits")] public uint AttributeCredits { get; set; }
    [Key("skill_credits")] public uint SkillCredits { get; set; }
    [Key("primary_start_areas")] public List<int> PrimaryStartAreas { get; set; } = [];
    [Key("secondary_start_areas")] public List<int> SecondaryStartAreas { get; set; } = [];
    [Key("skills")] public List<SkillCG> Skills { get; set; } = [];
    [Key("templates")] public List<TemplateCG> Templates { get; set; } = [];
    [Key("genders")] public List<MapEntry<int, SexCG>> GendersEntries { get; set; } = [];
    [Key("gender_bucket_idx")] public byte GenderBucketIdx { get; set; }
    [Key("gender_entry_order")] public List<int> GenderEntryOrder { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

[MessagePackObject]
public sealed partial class CharGen : IDatRecord {
    [Key("header")] public byte[] Header { get; set; } = [];
    [Key("starting_areas")] public List<StartArea> StartingAreas { get; set; } = [];
    [Key("heritage_bucket_idx")] public byte HeritageBucketIdx { get; set; }
    [Key("heritage_groups")] public List<MapEntry<uint, HeritageGroupCG>> HeritageGroupsEntries { get; set; } = [];
    [Key("heritage_entry_order")] public List<uint> HeritageEntryOrder { get; set; } = [];
    [Key("trailing_data")] public byte[] TrailingData { get; set; } = [];
    public void AfterDeserialize() => DatRecordMaps.AfterDeserialize(this);
    public void BeforeSerialize() => DatRecordMaps.BeforeSerialize(this);
}

